"""
LoRA Fine-Tuning for Granite 4.0-H-Micro (Hybrid Mamba-2/Transformer)

Trains task-specific LoRA adapters on synthetic data generated by the
synth pipeline (Phase 2). Outputs PEFT adapter checkpoints that can
be converted to GGUF for llama-cpp-python loading.

Architecture: granitehybrid — requires mamba_ssm ops monkey-patching
before model load.

Supported tasks:
    classification  — schema classification from file headers + sample rows
    mapping         — column name mapping (file columns → expected columns)
    rule_generation — SQL rule generation from column defs + CMMC objectives

Requirements:
    pip install torch transformers peft trl datasets accelerate bitsandbytes
    pip install mamba_ssm causal-conv1d

Usage:
    python train_lora.py --task classification --data-dir /workspace/data
    python train_lora.py --task all --data-dir /workspace/data --profile a100
    python train_lora.py --task all --data-dir /workspace/data --test
"""

# === Mamba SSM monkey-patching — MUST happen before any model import ===
from mamba_ssm.ops.triton.selective_state_update import selective_state_update
from mamba_ssm.ops.triton.ssd_combined import mamba_split_conv1d_scan_combined, mamba_chunk_scan_combined
import mamba_ssm
mamba_ssm.selective_state_update = selective_state_update
mamba_ssm.mamba_chunk_scan_combined = mamba_chunk_scan_combined
mamba_ssm.mamba_split_conv1d_scan_combined = mamba_split_conv1d_scan_combined

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Paths (defaults — overridden by CLI args for remote training)
ASSESSOS_DIR = Path(__file__).parent.parent.parent
SYNTH_OUTPUT_DIR = ASSESSOS_DIR / "scripts" / "synth_pipeline" / "output"
ADAPTERS_DIR = ASSESSOS_DIR / "llm_models" / "adapters"

# Task → training data file mapping
TASK_DATA = {
    "classification": SYNTH_OUTPUT_DIR / "classification_training.jsonl",
    "mapping": SYNTH_OUTPUT_DIR / "mapping_training.jsonl",
    "rule_generation": SYNTH_OUTPUT_DIR / "rule_generation_training.jsonl",
}

# Base model
BASE_MODEL_ID = "ibm-granite/granite-4.0-h-micro"

# Hardware profiles
# NOTE: load_in_4bit=False for ALL profiles — bitsandbytes quantized weights
# are incompatible with Mamba fast kernels (shape mismatch in F.linear).
# Model is small enough (~2GB bf16) that full precision fits everywhere.
PROFILES = {
    "local_16gb": {
        "batch_size": 1,
        "gradient_accumulation_steps": 16,
        "max_seq_length": 1280,
        "load_in_4bit": False,
    },
    "4090": {
        "batch_size": 8,
        "gradient_accumulation_steps": 4,
        "max_seq_length": 1280,
        "load_in_4bit": False,
    },
    "a100": {
        "batch_size": 32,
        "gradient_accumulation_steps": 1,
        "max_seq_length": 1280,
        "load_in_4bit": False,
    },
}

# Base training configuration
CONFIG = {
    "model_id": BASE_MODEL_ID,

    # LoRA config
    "lora_r": 16,
    "lora_alpha": 32,
    "lora_dropout": 0.05,
    # Granite 4.0-H-Micro module names:
    #   Attention (4 layers): self_attn.q_proj, k_proj, v_proj, o_proj
    #   Mamba (36 layers): mamba.in_proj, mamba.out_proj
    #   MLP (all 40 layers): shared_mlp.input_linear, shared_mlp.output_linear
    "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj", "in_proj", "out_proj", "input_linear", "output_linear"],

    # Training config (defaults — overridden by profile)
    "num_epochs": 3,
    "batch_size": 1,
    "gradient_accumulation_steps": 16,
    "learning_rate": 2e-4,
    "weight_decay": 0.01,
    "warmup_ratio": 0.06,
    "max_seq_length": 1280,

    # Quantization — MUST be False for Mamba hybrid (bitsandbytes incompatible)
    "load_in_4bit": False,
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_quant_type": "nf4",
}


def check_dependencies():
    """Check if required packages are installed."""
    required = ["torch", "transformers", "peft", "bitsandbytes", "datasets", "accelerate", "trl"]
    missing = []
    for pkg in required:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        print(f"Missing packages. Install with:\n  pip install {' '.join(missing)}")
        return False
    return True


def load_training_data(task: str, test_mode: bool = False) -> list[dict]:
    """Load JSONL training data for a task."""
    data_path = TASK_DATA.get(task)
    if not data_path or not data_path.exists():
        logger.error(f"Training data not found: {data_path}")
        logger.error("Run the synth pipeline first (Phase 2)")
        return []

    examples = []
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))

    if test_mode:
        examples = examples[:100]

    logger.info(f"Loaded {len(examples)} training examples for task '{task}'")
    return examples


def format_for_training(examples: list[dict]) -> list[dict]:
    """Convert Alpaca-format examples to native Granite chat format.

    Uses Granite's native special tokens:
        <|start_of_role|>{role}<|end_of_role|>{content}<|end_of_text|>
    """
    formatted = []
    for ex in examples:
        instruction = ex.get("instruction", "")
        inp = ex.get("input", "")
        output = ex.get("output", "")

        # Build user message
        user_content = instruction
        if inp:
            user_content += f"\n\n{inp}"

        text = (
            f"<|start_of_role|>system<|end_of_role|>You are a compliance analysis assistant.<|end_of_text|>\n"
            f"<|start_of_role|>user<|end_of_role|>{user_content}<|end_of_text|>\n"
            f"<|start_of_role|>assistant<|end_of_role|>{output}<|end_of_text|>\n"
        )
        formatted.append({"text": text})

    return formatted


def setup_model_and_tokenizer(config: dict):
    """Load model with optional QLoRA configuration."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

    model_id = config["model_id"]
    print(f"Loading model: {model_id}")

    if config["load_in_4bit"]:
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=getattr(torch, config["bnb_4bit_compute_dtype"]),
            bnb_4bit_quant_type=config["bnb_4bit_quant_type"],
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            attn_implementation="sdpa",
        )
        model = prepare_model_for_kbit_training(model)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            attn_implementation="sdpa",
        )

    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    lora_config = LoraConfig(
        r=config["lora_r"],
        lora_alpha=config["lora_alpha"],
        lora_dropout=config["lora_dropout"],
        target_modules=config["target_modules"],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    return model, tokenizer


def train_task(task: str, config: dict, output_dir: Optional[Path] = None,
               test_mode: bool = False, resume_from: str = None):
    """Train a LoRA adapter for a specific task."""
    from datasets import Dataset
    from trl import SFTTrainer, SFTConfig

    # Load data
    examples = load_training_data(task, test_mode)
    if not examples:
        return

    # Format for training
    formatted = format_for_training(examples)
    dataset = Dataset.from_list(formatted)

    # Split 90/10
    split = dataset.train_test_split(test_size=0.1, seed=42)
    train_dataset = split["train"]
    eval_dataset = split["test"]

    logger.info(f"Train: {len(train_dataset)}, Eval: {len(eval_dataset)}")

    # Output directory
    if output_dir is None:
        output_dir = ADAPTERS_DIR / task
    output_dir.mkdir(parents=True, exist_ok=True)

    run_name = f"assessos-{task}-{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    if test_mode:
        run_name += "-test"

    # Setup model
    model, tokenizer = setup_model_and_tokenizer(config)

    # SFTConfig (TRL 0.27+ — combines TrainingArguments + SFT settings)
    sft_config = SFTConfig(
        output_dir=str(output_dir / run_name),
        num_train_epochs=1 if test_mode else config["num_epochs"],
        per_device_train_batch_size=config["batch_size"],
        per_device_eval_batch_size=config["batch_size"],
        gradient_accumulation_steps=config["gradient_accumulation_steps"],
        learning_rate=config["learning_rate"],
        weight_decay=config["weight_decay"],
        warmup_ratio=config["warmup_ratio"],
        logging_steps=10,
        eval_strategy="steps",
        eval_steps=50 if not test_mode else 20,
        save_strategy="steps",
        save_steps=200 if not test_mode else 20,
        save_total_limit=3,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        bf16=True,
        report_to="none",
        gradient_checkpointing=True,
        max_grad_norm=1.0,
        lr_scheduler_type="cosine",
        # SFT-specific settings
        max_length=config["max_seq_length"],
        dataset_text_field="text",
        packing=True,
    )

    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        args=sft_config,
    )

    # Train
    if resume_from:
        logger.info(f"Resuming training from: {resume_from}")
    else:
        logger.info(f"Starting training for task '{task}'...")
    trainer.train(resume_from_checkpoint=resume_from)

    # Save final adapter
    final_dir = output_dir / run_name / "final"
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    logger.info(f"Saved adapter to {final_dir}")

    # Save training metadata
    eval_results = trainer.evaluate()
    meta = {
        "task": task,
        "base_model": config["model_id"],
        "training_examples": len(train_dataset),
        "eval_examples": len(eval_dataset),
        "eval_loss": eval_results.get("eval_loss"),
        "config": {k: v for k, v in config.items() if k != "target_modules"},
        "lora_r": config["lora_r"],
        "lora_alpha": config["lora_alpha"],
        "target_modules": config["target_modules"],
    }
    with open(output_dir / run_name / "training_metadata.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    logger.info(f"Eval loss: {eval_results.get('eval_loss', 'N/A')}")
    logger.info(f"Task '{task}' training complete!")


def main():
    global TASK_DATA
    parser = argparse.ArgumentParser(description="Train LoRA adapters for AssessOS")
    parser.add_argument("--task", choices=list(TASK_DATA.keys()) + ["all"], required=True, help="Which task to train")
    parser.add_argument("--profile", choices=list(PROFILES.keys()), help="Hardware profile")
    parser.add_argument("--epochs", type=int, help="Override number of epochs")
    parser.add_argument("--batch-size", type=int, help="Override batch size")
    parser.add_argument("--lr", type=float, help="Override learning rate")
    parser.add_argument("--rank", type=int, help="LoRA rank (r)")
    parser.add_argument("--no-4bit", action="store_true", help="Disable QLoRA")
    parser.add_argument("--output-dir", type=str, help="Override output directory")
    parser.add_argument("--data-dir", type=str, help="Override training data directory")
    parser.add_argument("--base-model", type=str, help="Override base model ID")
    parser.add_argument("--test", action="store_true", help="Quick test run with small subset")
    parser.add_argument("--resume", type=str, help="Resume from checkpoint path")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s", datefmt="%H:%M:%S")

    print("=" * 60)
    print("AssessOS LoRA Fine-tuning (Granite 4.0-H-Micro)")
    print("=" * 60)

    if not check_dependencies():
        return

    # Build config from base + profile + args
    config = CONFIG.copy()

    # Apply hardware profile (explicit or auto-detect)
    if args.profile:
        config.update(PROFILES[args.profile])
        print(f"Using profile: {args.profile}")
    else:
        try:
            import torch
            if torch.cuda.is_available():
                vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
                if vram_gb >= 40:
                    config.update(PROFILES["a100"])
                    print(f"Auto-detected {vram_gb:.1f}GB VRAM, using a100 profile")
                elif vram_gb >= 20:
                    config.update(PROFILES["4090"])
                    print(f"Auto-detected {vram_gb:.1f}GB VRAM, using 4090 profile")
                else:
                    config.update(PROFILES["local_16gb"])
                    print(f"Auto-detected {vram_gb:.1f}GB VRAM, using local_16gb profile")
        except Exception:
            print("Using default local_16gb profile")
            config.update(PROFILES["local_16gb"])

    # Override with explicit args
    if args.epochs:
        config["num_epochs"] = args.epochs
    if args.batch_size:
        config["batch_size"] = args.batch_size
    if args.lr:
        config["learning_rate"] = args.lr
    if args.rank:
        config["lora_r"] = args.rank
    if args.no_4bit:
        config["load_in_4bit"] = False
    if args.base_model:
        config["model_id"] = args.base_model

    # Override data directory
    if args.data_dir:
        data_dir = Path(args.data_dir)
        TASK_DATA = {
            "classification": data_dir / "classification_training.jsonl",
            "mapping": data_dir / "mapping_training.jsonl",
            "rule_generation": data_dir / "rule_generation_training.jsonl",
        }

    output_dir = Path(args.output_dir) if args.output_dir else None

    print(f"  Batch size: {config['batch_size']}")
    print(f"  Gradient accumulation: {config['gradient_accumulation_steps']}")
    print(f"  Effective batch: {config['batch_size'] * config['gradient_accumulation_steps']}")
    print(f"  Max seq length: {config['max_seq_length']}")
    print(f"  Epochs: {config['num_epochs']}")
    print(f"  Learning rate: {config['learning_rate']}")
    print(f"  4-bit quantization: {config['load_in_4bit']}")
    print(f"  Packing: True")

    tasks = list(TASK_DATA.keys()) if args.task == "all" else [args.task]

    for task in tasks:
        logger.info(f"\n{'=' * 60}")
        logger.info(f"Training LoRA adapter: {task}")
        logger.info(f"{'=' * 60}")
        train_task(task, config, output_dir, test_mode=args.test, resume_from=args.resume)

    logger.info("\nAll training complete!")


if __name__ == "__main__":
    main()